### ISSUE TITLE
[assignments.html] max padding at 30px

### ISSUE THREAD

**Issue by vincens2005** [vincens2005/myschoolapp-better-client#27]
change the css of full-container to this:
```css
.full-container {
    padding: min(3vw, 30px);
}
```
